# Generated by Django 3.1.7 on 2021-03-13 16:01

from django.db import migrations, models
import lampi.models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0002_alter_lampi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default=lampi.models.generate_association_code, max_length=32, unique=True),  # noqa
        ),
    ]
